### ISSUE TITLE
Checking prerelease shows unlisted packages

### ISSUE THREAD

**Issue by xqrzd** [adrian-pavel/visual-nuget#10]
I have a project that references Google.Protobuf. When checking prerelease in the updates tab, it shows an unlisted package as the newest version, https://www.nuget.org/packages/Google.Protobuf/4.0.0-rc2

Also, thanks for creating this! It's the best nuget package manager for VS Code I've used.

**Comment by adrian-pavel** [comment]
Hello, I fixed this issue and pushed a new version. Should be available soon: 0.2.0
I am glad you like it, thank you for the nice words. If you haven't already please consider reviewing it on the marketplace so that more people will find it.
