### ISSUE TITLE
Reload Update Panel when Update All

### ISSUE THREAD

**Issue by JohnGalt1717** [adrian-pavel/visual-nuget#16]
Right now if you select all on the update panel and then choose update all it updates properly, but then doesn't refresh the window so it looks like it didn't do anything if you don't look down in the terminal.

**Comment by adrian-pavel** [comment]
Yes, I was debating if I should fix this. Somehow I kinda liked still having the packages in the list as their version does change, but I can see this being confusing so I will try and fix it as soon as I can. Thanks for the feedback.
