### ISSUE TITLE
Integration with C# Dev Kit

### ISSUE THREAD

**Issue by tgtjam** [adrian-pavel/visual-nuget#25]
Missing integration with c# Dev Kit. 
It would be great to have the option to access the nugget from the solution explorer.
![image](https://github.com/adrian-pavel/visual-nuget/assets/77420482/63666b99-8270-4659-b5fa-e371c2dad78e)

**Comment by jiatao99** [comment]
+1

Thanks for this beautiful extension. It will be very useful to integrate with Dev Kit

**Comment by ouilol** [comment]
+1 Thanks for this extension.

**Comment by adrian-pavel** [comment]
Hello, I will try and look into this as I have some time now.

**Comment by adrian-pavel** [comment]
> Missing integration with c# Dev Kit. It would be great to have the option to access the nugget from the solution explorer. ![image](https://private-user-images.githubusercontent.com/77420482/259627862-63666b99-8270-4659-b5fa-e371c2dad78e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTk4MzEsIm5iZiI6MTcyNDA1OTUzMSwicGF0aCI6Ii83NzQyMDQ4Mi8yNTk2Mjc4NjItNjM2NjZiOTktODI3MC00NjU5LWI1ZmEtZTM3MWMyZGFkNzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZGVlMTVjYTIyNTI5N2Q0ZjBiNzkwOTliMTc1MDVkYTZjNGMxMjY5NmE5MzdlMTVlYWMzZmZmYzM4MWNhMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b9UmkT0tOXDujYD5nwFTtFwwovbqnSs8VtmwjIFXKoU)

Can't seem to find any obvious way to integrate with DevKit.
If you have any suggestion or know of other extensions that do integrate this way please let me know.

**Comment by adrian-pavel** [comment]
Closing for now. If anyone has any idea if/how this integration would be possible please let me know.

**Comment by CaCTuCaTu4ECKuu** [comment]
@adrian-pavel not sure how helpful will that be, but here's answer from ChatGPT
https://chatgpt.com/share/67282592-c0fc-800c-99eb-7bd7d844d151
That integration would be very in place
And thank's a lot for the extension
