### ISSUE TITLE
Opening Visual Nuget by Ctrl+Shift+P keys and select target project.

### ISSUE THREAD

**Issue by SignalMQ** [adrian-pavel/visual-nuget#28]
Now:
![image](https://github.com/adrian-pavel/visual-nuget/assets/77734001/096ebb46-ae5d-41b3-a09e-91aa0473257b)
Expected:
![image](https://github.com/adrian-pavel/visual-nuget/assets/77734001/43271cc4-8680-4860-ba04-722ed2e0e727)
![image](https://github.com/adrian-pavel/visual-nuget/assets/77734001/4a92c32d-c886-4975-989a-697266b506c3)

**Comment by adrian-pavel** [comment]
Added this functionality in v0.3.2. Thank you for the suggestion and please let me know if you spot any issues with it.

**Comment by adrian-pavel** [comment]
Fixed

**Comment by SignalMQ** [comment]
@adrian-pavel  Works fine, thank you!
