### ISSUE TITLE
Support Major.Minor.Build.Revision

### ISSUE THREAD

**Issue by pmahend1** [adrian-pavel/visual-nuget#35]
![image](https://github.com/user-attachments/assets/4763d0c1-0bf6-4909-af6c-2b94f17d728f)

Could you add support for this, it is assuming `Major.Minor.Build` is the latest versioin, however `Major.Minor.Build.Revision` is latest.
Also ensure this works with pre-release kind of versioning too.

Reference: https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/versioning

**Comment by adrian-pavel** [comment]
Done, thank you for the suggestion. It's available in v0.3.3. Let me know if you spot any issues please.
