### ISSUE TITLE
It would be great if the theme from Visual Studio Code itself was used

### ISSUE THREAD

**Issue by SignalMQ** [adrian-pavel/visual-nuget#41]
Now:
![image](https://github.com/user-attachments/assets/5c162b62-93c1-4245-9286-4a78fb63c84b)
Expected:
![image](https://github.com/user-attachments/assets/6143f7c0-4048-4ab8-9f33-294fcd43b0a7)

**Comment by adrian-pavel** [comment]
To be clear you mean the blue focused highlight instead of the orange one? 
Is there anything else different from your theme that you've noticed?

**Comment by SignalMQ** [comment]
Hello @adrian-pavel 
> To be clear you mean the blue focused highlight instead of the orange one? 
Yes, but not only blue highlight, I know insiders version have different color accent.
> Is there anything else different from your theme that you've noticed?
Not yet

**Comment by SignalMQ** [comment]
> To be clear you mean the blue focused highlight instead of the orange one? Is there anything else different from your theme that you've noticed?

Hello @adrian-pavel.
- Yes, but not only blue highlight, I know insiders version have different color accent.
- Not yet

**Comment by adrian-pavel** [comment]
Published v0.3.4 which contains this fix. Thanks again.
