### ISSUE TITLE
csproj in subdirectory not working

### ISSUE THREAD

**Issue by OneCyrus** [adrian-pavel/visual-nuget#5]
when opening a csproj in a subdirectory visual nuget can't list the installed packages. it only shows packages on the "browse" tab but other tabs are empty. looks like there is an issue with path resolution.

**Comment by adrian-pavel** [comment]
Thank you for letting me know. I will look into it tomorrow and update here. You most probably are right and it's an issue with how I handle the path. Should be an easy fix.

**Comment by adrian-pavel** [comment]
Fixed, merged and published. Thank you again for raising this issue.

**Comment by OneCyrus** [comment]
thank you! it works
