### ISSUE TITLE
multi selection for update 

### ISSUE THREAD

**Issue by OneCyrus** [adrian-pavel/visual-nuget#7]
it would be handy to have a multi selection like in visual studio to update more than one package at a time.

**Comment by adrian-pavel** [comment]
I agree, I was planning on adding such a feature in the future. I am actually planning to implement most of the features supported by the Visual Studio Package Manager.
But for now I first need to do some refactoring on the code. It could be a lot better. I focused on making the extension functional first but it's time to refactor.
I will leave this issue open and will update it once I get to implementing the feature.

**Comment by adrian-pavel** [comment]
Added this functionality on the Update tab in version 0.2.0. Should be available to download.
